"""Unit tests for infer_type.py generated by Assistant."""

import pytest
import numpy

from sastools.readers import infer_type


def test_infer_type_string():
    assert infer_type("hello world") == "String"


def test_infer_type_int32():
    assert infer_type(numpy.int32(123)) == "Int32"


def test_infer_type_int64():
    assert infer_type(123) == "Int64"
    assert infer_type(numpy.int64(123)) == "Int64"


def test_infer_type_float32():
    assert infer_type(numpy.float32(123.456)) == "Float32"


def test_infer_type_float64():
    assert infer_type(123.456) == "Float64"
    assert infer_type(numpy.float64(123.456)) == "Float64"


def test_infer_type_boolean():
    assert infer_type(True) == "Boolean"
    assert infer_type(False) == "Boolean"
    assert infer_type(1) != "Boolean"
    assert infer_type(0) != "Boolean"


def test_infer_type_invalid():
    with pytest.raises(ValueError):
        infer_type(None)
