"""Unit tests for pdhreader.py generated by Assistant."""

from pathlib import Path
import pytest
import re

from lxml import etree
import pandas as pd

from sastools.readers import PDHReader


@pytest.fixture
def pdh_reader():
    return PDHReader(path_to_directory="./tests/files/")


def test_pdh_reader_repr(pdh_reader):
    assert pdh_reader.__repr__() == "PDH Reader"


def test_pdh_reader_enumerate_available_files(pdh_reader):
    available_files = pdh_reader.enumerate_available_files()

    FILE_PATTERN = r"pdh_test_[\d]*"
    matches = lambda fname: bool(re.match(FILE_PATTERN, fname))

    assert len(available_files) == 2, f"Expected 2 files, got {len(available_files)}"
    assert all(
        matches(name) for name in available_files.values()
    ), f"File names have changed, got {available_files.values()}"


def test_pdh_reader_extract_data(pdh_reader):
    data = pdh_reader.extract_data("pdh_test_1")
    assert isinstance(data, pd.DataFrame)
    assert data.shape == (1091, 2)


def test_pdh_reader_extract_metadata(pdh_reader):
    metadata = pdh_reader.extract_metadata("pdh_test_1")
    assert isinstance(metadata, etree._ElementTree)


def test_pdh_reader_available_files(pdh_reader):
    available_files = pdh_reader.available_files
    assert isinstance(available_files, dict)
    assert len(available_files) == 2
    assert isinstance(list(available_files.values())[0], Path)
