"""Unit tests for seriesreader.py generated by Assistant."""

import pytest

from pyaniml import AnIMLDocument

from sastools.readers import SeriesReader

TEST_ID = ["x0__", "y0__"]


@pytest.fixture
def series_reader():
    with open("./tests/files/animl_test.animl", "r") as f:
        animl_doc = AnIMLDocument.fromXMLString(f.read())
    return SeriesReader(animl_doc=animl_doc)


def test_pdh_reader_repr(series_reader):
    assert series_reader.__repr__() == "AnIML Series-element Reader"


def test__parse_available_seriesIDs(series_reader):
    assert series_reader._parse_available_seriesIDs() == TEST_ID


def test_create_dataframe(series_reader):
    series_reader.selected_seriesIDs = TEST_ID
    df = series_reader.create_dataframe()
    assert df.shape == (8, 2)


def test_available_seriesIDs(series_reader):
    ids = series_reader.available_seriesIDs
    assert ids == ["x0", "y0"]


def test_selected_seriesIDs(series_reader):
    series_reader.selected_seriesIDs = TEST_ID
    selected = series_reader.selected_seriesIDs
    assert selected == TEST_ID
